#!/usr/bin/env bash
set -eou pipefail
cd "$(dirname "$0")"

cat > README.adoc <<EOF
= Git labs
:icons: font
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

// URIs
:uri-git-labs: https://github.com/paulojeronimo/git-labs
:uri-fork-a-repo: https://help.github.com/en/github/getting-started-with-github/fork-a-repo
:uri-asciidoctor: https://asciidoctor.org
:uri-what-is-asciidoc: https://asciidoctor.org/docs/what-is-asciidoc/
:uri-base58: https://learnmeabitcoin.com/guide/base58

// Attributes
:Git: https://git-scm.com/[Git^]
:Base58: <<base58,Base58>>
:Bash: https://www.gnu.org/software/bash/[Bash^]

Some labs to test {Git} features or solutions.
ifdef::backend-html5[]

NOTE: This HTML is generated from file link:README.adoc[].
Do not edit this file directly because it is generated by the script link:README.update.sh[].
endif::[]

<<contribution-guidelines,Contributions>> are wellcome! 😃 +
Fell free fork {uri-git-labs}[this repo^], add your lab and make me a pull request to add it.
Currently, these scripts only use {Bash}, and tools available in macOS and Linux distros like "sed" and "awk".

== Labs

$(for f in lab???.sh
  do
    sed -n '2p' $f | sed "s/^# Purpose: \(.*\)/* link:$f[]: \1/"
  done)

[[contribution-guidelines]]
=== Contribution guidelines

. Fork the repo {uri-git-labs}. ({uri-fork-a-repo}[Read about forking], if necessary).
. Name your lab as "lab<3 digits in {Base58}>".sh.
.. The first digit will identify you (the contributor).
.. Increment the last two digits as you add more labs.
. The second line inside the script should describe the purpose of the lab using the {uri-what-is-asciidoc}[AsciiDoc syntax].
.. This line should have the format "Purpose: <description>" as in the following example (extracted from link:lab111.sh[]).
Please, write the description in a resumed way.
+
----
include::lab111.sh[lines=2]
----
+
. After write your lab, update this README.adoc by invoking the link:README.update.sh[] script.
.. If you have {uri-asciidoctor}[asciidoctor^] installed, use the argument "--html" to this script generate and see the README.html.

== Utilities

[[base58]]
. {Base58} encode/decode:
.. {uri-base58}
.. https://incoherency.co.uk/base58/
EOF

! [ "${1:-}" == "--html" ] || {
  asciidoctor README.adoc
  for f in lab???.adoc; do asciidoctor $f; done
}
