[[contribution-guidelines]]
= Contribution guidelines

. Fork the repo {uri-paulojeronimo-git-labs}. {uri-github-fork-a-repo}[Read about forking], if necessary.
. Name your lab as "lab<3 digits in {Base58}>".sh.
.. The first digit will identify you (the contributor).
.. Increment the last two digits as you add more labs.
. Inside your script, describe the purpose of it by writing its second line using the {uri-what-is-asciidoc}[AsciiDoc syntax].
.. This line should have the format "Purpose: <description>" as in the following example (extracted from link:lab111.sh[]).
Please, write a description in a resumed way.
+
----
include::../lab111.sh[lines=2]
----
+
. Commit the `lab???.sh` script inside your fork.
. Update this `README.adoc` by invoking the link:README.update.sh[] script.
.. If you have {uri-asciidoctor}[asciidoctor^] installed, use the argument `--html` to this script to generate a `index.html` file.
In this case, you can also use the argument `--serve` to start a `ruby` httpd locally and access http://localhost:8000 to see its content.
. {uri-github-creating-a-pull-request-from-a-fork}[Make a pull request^].
